### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by studiophoyo** [B16f00t/whapa#125]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared\_CommonRedist\vcredist\2013\whapa\whapa-master\libs\whagodri.py", line 443, in <module>
    getMultipleFiles(backup, filter_file)
  File "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared\_CommonRedist\vcredist\2013\whapa\whapa-master\libs\whagodri.py", line 275, in getMultipleFiles
    for entry, size in files_dict.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by studiophoyo** [comment]
Help

**Comment by B16f00t** [comment]
Use the latest version

**Comment by studiophoyo** [comment]
Thanks, closing this
