### ISSUE TITLE
Authentication for GDrive failes (BAD_COOKIE)

### ISSUE THREAD

**Issue by hashworks** [B16f00t/whapa#131]
Running the Google Drive Extractor fails for me:

```
    -------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Requesting Google access...
Granted

Requesting authentication for Google Drive...
Failed

{'SID': 'BAD_COOKIE', 'LSID': 'BAD_COOKIE', 'Auth': 'REDACTED', 'Token': 'REDACTED', 'services': 'ah,apps,CPanel,sprose,mail,devconsole,sitemaps,talk,hist,cl,writely,jotspot,contacts,legaldiscovery,multilogin,groups2,sierra,omaha,friendview,android,backup,wise,youtube,hasacceptedpagestos,androidconsole,mymaps,googleplay,androiddeveloper,urlshortener,local,classroom,tasks,chromiumsync,appsscript,memento,jamboardcore,dynamite,mobilesync,grandcentral,cloudconsole,ahsid,HOSTED', 'firstName': 'Justin', 'lastName': 'Kromlinger,', 'GooglePlusUpdate': '0', 'Email': 'REDACTED'}
Traceback (most recent call last):
  File "/usr/local/src/whapa/libs/whagodri.py", line 382, in <module>
    wa_backup = WaBackup(**getConfigs())
  File "/usr/local/src/whapa/libs/whagodri.py", line 45, in __init__
    error(token)
  File "/usr/local/src/whapa/libs/whagodri.py", line 199, in error
    if "BadAuthentication" in failed:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by hashworks** [comment]
Closed: This was related to GSuite Mobile Device Management. Deactivating it fixed the error.

**Comment by jorgeortizfuentes** [comment]
I also have this problem. I am using a Google Workspace account. How exactly did you solve it?

**Comment by hashworks** [comment]
I think it's this one, but I'm not sure…

You might need to translate that from German to English.
![example](https://fb.hash.works/pjRYvvab/)

The important part is "Management option: not managed".
