### ISSUE TITLE
Keyerror: 'backups'

### ISSUE THREAD

**Issue by EFoZM** [B16f00t/whapa#135]
Requesting Google access...
Granted

Requesting authentication for Google Drive...
Granted

Traceback (most recent call last):
  File "C:\Users\EFoZM\Desktop\New Folder\whapa\libs\whagodri.py", line 418, in <module>
    for backup in backups:
  File "C:\Users\EFoZM\Desktop\New Folder\whapa\libs\whagodri.py", line 70, in list_path
    for item in page[last_component]:
KeyError: 'backups'

I backed up my WhatsApp a couple of hours ago. What should I do?

**Comment by A-Passenger** [comment]
yeah it's the same for me and i couldn't fix it

**Comment by B16f00t** [comment]
This error occurs when you do not have a correct backup in google drive
