### ISSUE TITLE
Getting multiple error with connectionpool.py and ssl.py

### ISSUE THREAD

**Issue by crazyfrog89** [B16f00t/whapa#139]
httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 598, in urlopen
    httplib_response = self._make_request(conn, method, url,
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake

**Comment by crazyfrog89** [comment]
i was actually trying to use WhAGoDrive feature. When i tried listing the files, it lists all the file name but when i try to download by giving "All" i am getting error. Like you suggested, tried with previous version 3.8 for which i am getting the below error.
[i] Searching...

Requesting Google access...
Granted

Requesting authentication for Google Drive...
Granted

Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket

Kindly help

**Comment by B16f00t** [comment]
Downgrade your requests version. Use whapa requeriments
