### ISSUE TITLE
Whagodri not working

### ISSUE THREAD

**Issue by crazyfrog89** [B16f00t/whapa#150]
i am getting the below error
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

It was working fine and downloads were happening 10 mins back. But wifi got turned off and when i tried again with the same account with same request, getting the above errors. Also i tried multiple times running whagodri, it is not working. Can you please help me here
![whagodriv](https://user-images.githubusercontent.com/91891006/147312257-f532de1f-f006-4799-80a3-3b0e786ed3b7.PNG)

**Comment by B16f00t** [comment]
You have to downgrade your request python library. Use the versions include in the requirements file.
