### ISSUE TITLE
"BadAuthentication" error in WhaGoDri

### ISSUE THREAD

**Issue by nicolaslazo** [B16f00t/whapa#172]
Hello, I was wondering if maybe you knew what I'm doing wrong when I'm trying to authenticate? I get a `{'Error': 'BadAuthentication'}` message whenever I try to run WhaGoDri.

I've tried setting my email address and device ID as I found through ADB into my config. Then I tried
1. Getting an app password from security > app passwords > creating a 16-char password for a service named "Whapa". OAuth token field is empty
2. No password. I went to the OAuth 2.0 playground, got an authorisation code for all read-only Drive permissions
  * https://www.googleapis.com/auth/drive.metadata.readonly
  * https://www.googleapis.com/auth/drive.photos.readonly
  * https://www.googleapis.com/auth/drive.readonly
  Exchanged that for a token and copied and pasted that into my config. This is where I got that token from (text fields emptied for security reasons)

![image](https://user-images.githubusercontent.com/45973144/173740788-e0f2a266-e3ee-4acd-a99b-36756eafbfe7.png)

No luck so far. Has anyone else been having this problem? Am I misconfiguring something?

Thanks!

**Comment by B16f00t** [comment]
If you are receving BadAutenthication.
 "1. Check that your email and password are correct in the settings file."
 "2. Your are using a old python version. Works >= 3.8."
 "3. Update requirements, use in a terminal: 'pip3 install --upgrade -r ./doc/requirements.txt' or 'pip install --upgrade -r ./doc/requirements.txt\n"
  "4. Your OAuth token configured in the settings file may have expired. The token will be deleted and you will have to log in again.")"

If you have the Ouath token you can write it down in the settings.cfg file and it will log in without username and password.
If your account has 2FA enabled or is a GSuite account, whapa will display a needbrowser bug, and a URL that will automatically open in a browser and once you log in, the program will automatically add your OUATH token to the setting file. So it's automatic...

**Comment by sheeddy** [comment]
i have OAUTH token but... i can't login without username and password...

so i need use outh token with username and pass ....

**Comment by digilabtecHD** [comment]
Hello, I have the following error, described below.
I'm using Python version 3.9.

  __      __.__             ________      ________        .__
    /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
    \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
     \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
      \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
           \/       \/     \/        \/              \/

    -------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Enter your password for :
Requesting authentication for Google Drive...
Traceback (most recent call last):
  File "C:\Users\Prado\Desktop\whapa-master\libs\whagodri.py", line 553, in <module>
    wa_backup = WaBackup(**getConfigs())
  File "C:\Users\Prado\Desktop\whapa-master\libs\whagodri.py", line 120, in __init__
    auth = gpsoauth.perform_oauth(
NameError: name 'gpsoauth' is not defined

**Comment by sekedus** [comment]
use `oauth_token` instead, [read here](https://github.com/giacomoferretti/whatsapp-backup-downloader-decryptor#getting-the-oauth_token).
