### ISSUE TITLE
New version not working anymore

### ISSUE THREAD

**Issue by broche0** [B16f00t/whapa#174]
This is the error i got everytime with new version

Traceback (most recent call last):
  File "/Users/xxxx/whapa-master/libs/whagodri.py", line 553, in <module>
    wa_backup = WaBackup(**getConfigs())
  File "/Users/xxxx/whapa-master/libs/whagodri.py", line 43, in __init__
    token = gpsoauth.perform_master_login(email=gmail, password=password, android_id=android_id)
  File "/Users/xxxx/whapa-master/libs/gpsoauth/__init__.py", line 138, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/Users/xxxx/whapa-master/libs/gpsoauth/__init__.py", line 76, in _perform_auth_request
    session.mount(AUTH_URL, AuthHTTPAdapter())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/Users/xxxx/whapa-master/libs/gpsoauth/__init__.py", line 68, in init_poolmanager
    context.options &= ~ssl_.OP_NO_TICKET
AttributeError: module 'urllib3.util.ssl_' has no attribute 'OP_NO_TICKET'

**Comment by B16f00t** [comment]
pip3 install --upgrade -r ./doc/requirements.txt

You have requirements incomplete. The tool works perfectly
