### ISSUE TITLE
error: couldn't recognize data in image file

### ISSUE THREAD

**Issue by broche0** [B16f00t/whapa#180]
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "whapa-gui.py", line 1543, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 70, in __init__
    self.iconlogo = PhotoImage(file=self.icons[0])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/whapa-master/images/logo.png"

**Comment by hyperdregon** [comment]
hey, did you fix this issue?
