### ISSUE TITLE
Problem using Whagodri

### ISSUE THREAD

**Issue by and977** [B16f00t/whapa#46]
Hi, I have installed Python 3.8.1, and the installation of requirements was ok.
Now when I try to make any action on the Whagodri TAB always the same error appears on the terminal:

```
[i] Searching...

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\configparser.py", line 789, in ge
t
    value = d[option]
  File "C:\Program Files (x86)\Python38-32\lib\collections\__init__.py", line 89
1, in __getitem__
    return self.__missing__(key)            # support subclasses that define __m
issing__
  File "C:\Program Files (x86)\Python38-32\lib\collections\__init__.py", line 88
3, in __missing__
    raise KeyError(key)
KeyError: 'devid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 58, in getConfigs
    devid = config.get('auth', 'devid')
  File "C:\Program Files (x86)\Python38-32\lib\configparser.py", line 792, in ge
t
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'devid' in section: 'auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 258, in <module>
    getConfigs()
  File ".\libs\whagodri.py", line 65, in getConfigs
    except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'
```

I'm not even a dummy with Python, so I can't understand what's happening.
Anyone can help me?

Thanks in advance

**Comment by B16f00t** [comment]
problem installing requirements  #32
