### ISSUE TITLE
Error when I try to open Whapa.py

### ISSUE THREAD

**Issue by XenonKusanagi** [B16f00t/whapa#57]
Traceback (most recent call last):
  File "whapa-gui.py", line 1049, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 521, in __init__
    update = (request.text.split('itemprop="about">')[1]).split("</span>")[0].strip("\n ")
IndexError: list index out of range

**Comment by B16f00t** [comment]
Fix in v1.16
