### ISSUE TITLE
tkinter - couldn't recognize data in image file

### ISSUE THREAD

**Issue by Flatcova** [B16f00t/whapa#65]
hi, I just install the requirements and all but when I run the command this error comes up, I'm running python 3.8.2 on macOS

```
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "whapa-gui.py", line 1049, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 54, in __init__
    self.iconlogo = PhotoImage(file=self.icons[0])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4061, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Volumes/windows 10/whapa/images/logo.png"
```

**Comment by B16f00t** [comment]
Whapa only works in Windows and Linux. It has never tested in MacOs.

**Comment by grishka** [comment]
Now it's been tested on macOS and it clearly didn't work. I'm getting the same error.

**Comment by Viveur** [comment]
Also gettting this error under MacOS
