### ISSUE TITLE
 SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?

### ISSUE THREAD

**Issue by xCuzImPro** [B16f00t/whapa#7]
```Bash

user@user-PC MINGW64 /d/Download/whapa-master/whapa-master
$ pip install -r ./doc/requirements.txt
Collecting pycryptodome (from -r ./doc/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/cf/5d/8712c03b122bbd53ce9b5471f4333bb3d7b6aa8a62b7a64bfecfe264235b/pycryptodome-3.7.0-cp37-cp37m-win_amd64.whl
Collecting colorama (from -r ./doc/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Collecting BeautifulSoup (from -r ./doc/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-5rp5k6sp\BeautifulSoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?

Command "python setup.py egg_info" failed with error code 1 in C:\Users\USERNAME\AppData\Local\Temp\pip-install-5rp5k6sp\BeautifulSoup\

user@user-PC MINGW64 /d/Download/whapa-master/whapa-master
```

**Comment by xCuzImPro** [comment]
done i switch py from 3.7 to 2.7.3 

```Bash
user@user-PC MINGW64 /d/Download/whapa-master/whapa-master
$ pip install -r ./doc/requirements.txt
Collecting pycryptodome (from -r ./doc/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/14/6f/5abf7e3e87aa71bf120a4ff94581f97392a5b583c8a763ba34ad5bb3ff22/pycryptodome-3.7.0-cp27-cp27m-win_amd64.whl (7.9MB)
Collecting colorama (from -r ./doc/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Collecting BeautifulSoup (from -r ./doc/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
Collecting configparser (from -r ./doc/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting gpsoauth (from -r ./doc/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/96/a1/2b366c602ee081def4dd80624581dfa8eb23d20c5a51f8a2591c40fa8d41/gpsoauth-0.4.1.tar.gz
Collecting pycryptodomex>=3.0 (from gpsoauth->-r ./doc/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/6d/a3/2dbd14dfb2dfdffd253f85530c17e18bf07127bf19686de64ef622959338/pycryptodomex-3.6.6-cp27-cp27m-win_amd64.whl (7.8MB)
Requirement already satisfied: requests in c:\python27\lib\site-packages (from gpsoauth->-r ./doc/requirements.txt (line 5)) (2.20.0)
Requirement already satisfied: idna<2.8,>=2.5 in c:\python27\lib\site-packages (from requests->gpsoauth->-r ./doc/requirements.txt (line 5)) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests->gpsoauth->-r ./doc/requirements.txt (line 5)) (2018.10.15)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python27\lib\site-packages (from requests->gpsoauth->-r ./doc/requirements.txt (line 5)) (1.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests->gpsoauth->-r ./doc/requirements.txt (line 5)) (3.0.4)
Installing collected packages: pycryptodome, colorama, BeautifulSoup, configparser, pycryptodomex, gpsoauth
  Running setup.py install for BeautifulSoup: started
    Running setup.py install for BeautifulSoup: finished with status 'done'
  Running setup.py install for configparser: started
    Running setup.py install for configparser: finished with status 'done'
  Running setup.py install for gpsoauth: started
    Running setup.py install for gpsoauth: finished with status 'done'
Successfully installed BeautifulSoup-3.2.1 colorama-0.4.0 configparser-3.5.0 gpsoauth-0.4.1 pycryptodome-3.7.0 pycryptodomex-3.6.6
```

**Comment by B16f00t** [comment]
Try this: sudo pip2 install BeautifulSoup

**Comment by xCuzImPro** [comment]
Thanks for your answer, I think that is installed? 
I have a Windows PC 😑 I can try your solution.
