### ISSUE TITLE
makedirs error

### ISSUE THREAD

**Issue by xCuzImPro** [B16f00t/whapa#8]
Windows 10
git Bash
1,3 GB Backup.

```Bash
    [+] Number: 4135 / 4156
        [-] Thread-06=> Downloaded: 'WhatsApp\Media\WhatsApp Voice Notes\201550\PTT-20151206-WA0008.aac'

[i] Downloads finished
makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'WhatsApp\\Media\\WhatsApp Images'

Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "whagodri.py", line 179, in run
    process_data(self.name, self.q)
  File "whagodri.py", line 188, in process_data
    getMultipleFilesThread(data['bearer'], data['entries_r'], data['local'], data['entries_m'], threadName)
  File "whagodri.py", line 198, in getMultipleFilesThread
    os.makedirs(os.path.dirname(local))
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'WhatsApp\\Media\\WhatsApp Images\\Sent'





Exception in thread Thread-39:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "whagodri.py", line 179, in run
    process_data(self.name, self.q)
  File "whagodri.py", line 188, in process_data
    getMultipleFilesThread(data['bearer'], data['entries_r'], data['local'], data['entries_m'], threadName)
  File "whagodri.py", line 198, in getMultipleFilesThread
    os.makedirs(os.path.dirname(local))
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'WhatsApp\\Media\\WhatsApp Images'

Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "whagodri.py", line 179, in run
    process_data(self.name, self.q)
  File "whagodri.py", line 188, in process_data
    getMultipleFilesThread(data['bearer'], data['entries_r'], data['local'], data['entries_m'], threadName)
  File "whagodri.py", line 198, in getMultipleFilesThread
    os.makedirs(os.path.dirname(local))
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'WhatsApp\\Media\\WhatsApp Images'



Carsten@Carsten-PC MINGW64 /d/Download/whapa-master/whapa-master
$ py -2 whagodri.py -h

     __      __.__             ________      ________        .__
    /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
    \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
     \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
      \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
           \/       \/     \/        \/              \/

    ------------ Whatsapp Google Drive Extractor v0.1 ------------

usage: whagodri.py [-h] [-i | -l | -lw | -p FilePath BackupID | -s] [-f]

Extract your Whatsapp files from Google Drive

optional arguments:
  -h, --help            show this help message and exit
  -i, --info            Show information about Whatsapp backups
  -l, --list            List all available files
  -lw, --list_whatsapp  List Whatsapp backups
  -p FilePath BackupID, --pull FilePath BackupID
                        Pull a file from Google Drive
  -s, --sync            Sync all files locally
  -f, --flush           Flush log file to sync from the beginning
````

**Comment by B16f00t** [comment]
Sometimes it is not possible to download all the files from the cloud, because of version changes or because they are no longer accessible and the index remains, and when the tool tries to download them they fail.

Try Linux (Debian, Ubuntu,...) better than Windows and feedback.

**Comment by xCuzImPro** [comment]
Okay thanks your answer,
My backup is broken on the cloud. 
That's why I wanted to download it before Google Drive does ... what Whatsapp they have announced.

I testing on the weekend your solution.
