### ISSUE TITLE
AttributeError: Module gpsoauth.google

### ISSUE THREAD

**Issue by Scaflown** [B16f00t/whapa#95]
Hi, I have this problem.
![image](https://user-images.githubusercontent.com/82222111/114190808-1aa6aa00-9922-11eb-894c-ba3d514b081f.png)

**Comment by B16f00t** [comment]
Install a previous version of gpsoauth.
 pip install gpsoauth==0.4.3

**Comment by shuriken-444** [comment]
i tried what you suggested but still not working, its weird, since iv been using it before and not problems at all.. any tip to makes it run again?

**Comment by B16f00t** [comment]
What is your gpsoauth version?

**Comment by shuriken-444** [comment]
gpsoauth
Version: 1.0.0

**Comment by shuriken-444** [comment]
i actually tried installing gpsoauth==0.4.3, but still the same output, no luck yet.

**Comment by shuriken-444** [comment]
output:

Requesting Auth for Google....
Failed

Error=BadAuthentication

   Workaround
-----------------
1. Check that your email and password are correct in the settings file, if so change your google password and try again.
2. Your are using a old python version. Works > 3.7.7.
3. Update the gpsoauth dependency to its latest version, use in a terminal: 'pip install -U gpsoauth' or 'pip3 install -U gpsoauth'
 
All workaround tips were done, no changes. Thanks for your time mate.

**Comment by shuriken-444** [comment]
-------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Traceback (most recent call last):
  File "/home/kali/whapa/./libs/whagodri.py", line 318, in <module>
    bearer = getGoogleDriveToken(getGoogleAccountTokenFromAuth())
  File "/home/kali/whapa/./libs/whagodri.py", line 78, in getGoogleAccountTokenFromAuth
    encpass = google.signature(gmail, passw, android_key_7_3_29)
AttributeError: module 'gpsoauth.google' has no attribute 'signature'

**Comment by B16f00t** [comment]
You are using a old version

**Comment by thecreed** [comment]
it appears that signature method has changed to https://github.com/simon-weber/gpsoauth/commit/6c5cbeb7466d67d84746b562c9159ab543fbeb68

**Comment by shuriken-444** [comment]
i was suspicious about the "you have an old version statement" since im running python3.9, so whats the roundabout in this construct_signature issue?

**Comment by B16f00t** [comment]
I will change it in the next version.
